apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: temporal-profiler

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: temporal-profiler

images:
  - name: ghcr.io/temporal-profiling/temporal-profiler
    newTag: latest
