apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: temporal-profiler
  namespace: temporal-profiler-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal-profiler
